name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - x86
          - x86_64
    runs-on: ubuntu-latest
    container:
      image: 'docker://fabernovel/android:api-29-ndk-v1.1.1'
    steps:
      - uses: actions/checkout@v2
      - name: run shell
        env:
          ARCH: '${{ matrix.arch }}'
          ANDROID_NDK_HOME: /opt/android/sdk/ndk/21.0.6113669
        run: bash build-android.sh
      - uses: montudor/action-zip@v0.1.0
        with:
          args: 'zip ${{ matrix.arch }}.zip ./openssl/*.a ./openssl/*.so'
      - name: Upload a Build Artifact
      - uses: actions/upload-artifact@v2
      - with:
          path: '${{ github.workspace }}/openssl/${{ matrix.arch }}.zip'
  upload:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - uses: montudor/action-zip@v0.1.0
        with:
          args: >-
            unzip arm.zip -d armeabi-v7a && unzip arm64.zip -d arm64-v8a &&
            unzip x86.zip -d x86 && unzip x86_64.zip -d x86_64 && ls && rm *.zip
            &&zip -r artifact.zip .
      - uses: actions/upload-artifact@v2
        with:
          path: '${{ github.workspace }}/artifact.zip'
